init:
- type src\ChangelogProvider.Generator\ChangelogProvider.Generator.fsproj

dotnet_csproj:
  patch: true
  file: '**\*.fsproj'
  version: '{version}'
  package_version: '{version}'

build_script:
- type src\ChangelogProvider.Generator\ChangelogProvider.Generator.fsproj

test: off
