image: Visual Studio 2015

version: 1.0.0-beta{build}

cache:
  - packages -> paket.lock

test: off

pull_requests:
  do_not_increment_build_number: true

nuget:
  project_feed: true
  disable_publish_on_pr: true

build_script:
  - ps: .\build.cmd Pack

artifacts:
  - path: artifacts\*.nupkg

for:
-
  branches:
    only:
      - master

  deploy:
    provider: NuGet
    api_key:
      secure: L7odOFMnsYXsr9xOYNQDYWd50oiW4exiv+EubBMfPYVYfkQ/56T9p+D8wtmPFpHL
    skip_symbols: true
    artifact: /.*\.nupkg/